[package]
name = "yu-engine-manager"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flate2.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
zip.workspace = true
yu-engine-api = { path = "../yu-engine-api" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
