[package]
name = "yu-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "yu"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
yu-capability-image = { path = "../yu-capability-image" }
yu-capability-psd = { path = "../yu-capability-psd" }
yu-runtime-psd = { path = "../yu-runtime-psd" }
yu-core = { path = "../yu-core" }
yu-engine-image-rs = { path = "../yu-engine-image-rs" }
yu-engine-manager = { path = "../yu-engine-manager" }

[dev-dependencies]
image.workspace = true
serde_json.workspace = true
sha2.workspace = true
